DELETE FROM plugin WHERE id = "81875";
DELETE FROM plugin_sid where plugin_id = "81875";
INSERT INTO plugin (id, type, name, description, product_type, vendor) VALUES (81875, 1, 'haproxy', 'HAProxy', NULL, 'HAProxy');
-- INSERT IGNORE INTO software_cpe (cpe, name, version, line, vendor, plugin) VALUES ('cpe:/o:', 'HAProxy','-','','HAProxy', 'haproxy:81875');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 1, 3, 119, 1, 1, 'HAProxy TCP Session');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 200, 13, 109, 1, 1, 'HAProxy HTTP: OK');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 201, 13, 109, 1, 1, 'HAProxy HTTP: Created');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 202, 13, 109, 1, 1, 'HAProxy HTTP: Accepted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 203, 13, 117, 1, 1, 'HAProxy HTTP: Non-Authorative Information');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 204, 13, 117, 1, 1, 'HAProxy HTTP: No Content');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 205, 13, 111, 1, 1, 'HAProxy HTTP: Reset Content');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 206, 13, 117, 1, 1, 'HAProxy HTTP: Partial Content');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 300, 13, 117, 1, 1, 'HAProxy HTTP: Multiple Choices');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 301, 13, 114, 1, 1, 'HAProxy HTTP: Moved Permanently');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 302, 13, 114, 1, 1, 'HAProxy HTTP: Moved Temporarily');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 303, 13, 117, 1, 1, 'HAProxy HTTP: See Other');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 304, 13, 117, 1, 1, 'HAProxy HTTP: Not Modified');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 305, 13, 115, 1, 1, 'HAProxy HTTP: Use Proxy');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 400, 13, 116, 1, 1, 'HAProxy HTTP: Bad Request');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 401, 2, 93, 1, 1, 'HAProxy HTTP: Authorization Required');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 402, 13, 117, 1, 1, 'HAProxy HTTP: Payment Required');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 403, 13, 113, 1, 1, 'HAProxy HTTP: Forbidden');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 404, 13, 118, 1, 1, 'HAProxy HTTP: Not Found');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 405, 13, 116, 1, 1, 'HAProxy HTTP: Method Not Allowed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 406, 13, 116, 1, 1, 'HAProxy HTTP: Not Acceptable (encoding)');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 407, 13, 115, 1, 1, 'HAProxy HTTP: Proxy Authentication Required');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 408, 13, 117, 1, 1, 'HAProxy HTTP: Request Timed Out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 409, 13, 116, 1, 1, 'HAProxy HTTP: Conflicting Request');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 410, 13, 117, 1, 1, 'HAProxy HTTP: Gone');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 411, 13, 116, 1, 1, 'HAProxy HTTP: Content Length Required');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 412, 13, 116, 1, 1, 'HAProxy HTTP: Precondition Failed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 413, 13, 116, 1, 1, 'HAProxy HTTP: Request Entity Too Long');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 414, 13, 116, 1, 1, 'HAProxy HTTP: Request URI Too Long');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 415, 13, 116, 1, 1, 'HAProxy HTTP: Unsupported Media Type');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 500, 13, 116, 1, 1, 'HAProxy HTTP: Internal Server Error');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 501, 13, 116, 1, 1, 'HAProxy HTTP: Not implemented');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 502, 13, 116, 1, 1, 'HAProxy HTTP: Bad Gateway');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 503, 13, 116, 1, 1, 'HAProxy HTTP: Service Unavailable');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 504, 13, 116, 1, 1, 'HAProxy HTTP: Gateway Timeout');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`category_id`,`subcategory_id`,`reliability`,`priority`,`name`) VALUES (81875, 505, 13, 116, 1, 1, 'HAProxy HTTP: HTTP Version Not Supported');
